server:
  port: 9000
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.101.138.153:3316/dbtools?serverTimezone=GMT%2B8
    username: dbadmin
    password: dbadmin
    connectionProperties:
  mvc:
    view:
      prefix: /pages/
      suffix: .html

xml:
  model:
    appname: javaDbAutoTools
    genpath: "design\\model\\original\\"
    dsxmlPath: "design\\model\\dataSource.xml"
    ddxmlPath: "design\\model\\handleXml\\dd_{}.xml"
    opXmlPath: "design\\model\\operator.xml"

fileuploadPath: "upload\\"